project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Caleb Kwon"
  google-analytics:
    tracking-id: "G-4XFXNXT3RJ"
    anonymize-ip: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
    right:
      - icon: envelope
        href: mailto:caleb.kwon@mccombs.utexas.edu
      - icon: google
        href: https://scholar.google.com/citations?user=mBw3GmIAAAAJ&hl=en

format:
  html:
    theme:
      light: flatly
    css:
      - styles.css
      - homepage-fixes.css
    toc: false
