---
title: "&nbsp;"
output: 
  html_document:
      css: styles.css

---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-165847699-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-165847699-1');
</script>


<link rel="stylesheet" href="styles.css" type="text/css">

<style type="text/css">
  body{
  font-size: 10pt;
}
</style>

<style>
html{
    width:100%;
    height:100%;
}
body{
    width:100%;
    height:100%;
}
</style>


:::::: {.columns}
::: {.column width="48%" data-latex="{0.48\textwidth}"}
# Basics

  - [Installing and Loading Packages](https://www.youtube.com/watch?v=AhTA-jwPJjo) [3:17]
    + Perfect video if you hate writing out `library()` a million times and worrying if the package you want to load is already installed. 
  - [Importing .CSV, .XLSX, .DTA, and .MAT datasets](https://www.youtube.com/watch?v=c91yQG0L1q0) [5:35]
    + Need to import simulation results from Matlab? Or have a coauthor who only works with Stata? 
:::
::: {.column width="1%" data-latex="{0.04\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::
:::::: {.column width="48%" data-latex="{0.48\textwidth}"}

# Data Cleaning/Wrangling

  - [Winsorizing and Trimming](https://www.youtube.com/watch?v=A9j_gdkdmwY) [6:26]
  - [Changing Variable/Column Names](https://www.youtube.com/watch?v=b919dCEyeuw) [1:07]
  - [Deleting Variables/Columns](https://www.youtube.com/watch?v=1TZQvYGnTkY) [2:25]
  - [Counting NA Rows/Observations](https://www.youtube.com/watch?v=3isChjlemC4) [0:59]
  - [Deleting NA Rows/Observations](https://www.youtube.com/watch?v=PRw79bzhnZM) [2:14]
  - [Replacing NA Rows/Observations](https://www.youtube.com/watch?v=9EDsJhvqsQk) [1:49]
:::
::::::

<!-- Second set of columns begins here  -->

:::::: {.columns}
::: {.column width="48%" data-latex="{0.48\textwidth}"}

  
# Data Exploration

  - Correlation Plots
  
:::
::: {.column width="1%" data-latex="{0.04\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::
:::::: {.column width="48%" data-latex="{0.48\textwidth}"}

# Regression Analysis 

  - [Robust and Clustered Standard Errors](https://www.youtube.com/watch?v=wTMKTpXKgOE) [4:42]
    + Goes over HC0 ~ HC3, One-way and Two-way Clustered Standard Errors. 
:::
::::::

<!-- Second set of columns begins here  -->

:::::: {.columns}
::: {.column width="48%" data-latex="{0.48\textwidth}"}

  
# Caleb's Recommended Packages

  - [fixest](https://www.youtube.com/watch?v=6r8FzYmfsjk) [7:57]
    + A must have for empirical researchers (Estimates linear/non-linear models, a bunch of standard errors, and makes exporting results into $LaTeX$ an absolute breeze).
  - [sandwich]
    + Computes all sorts of standard errors (HC0 ~ HC5)
  - [irlba]
    + Computes singular values of large matrices super-super fast. 
  
:::
::: {.column width="1%" data-latex="{0.04\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::
:::::: {.column width="48%" data-latex="{0.48\textwidth}"}

# Machine Learning 

:::
::::::


<!-- Third set of columns begins here  -->

:::::: {.columns}
::: {.column width="48%" data-latex="{0.48\textwidth}"}

  
# Data Visualization

  - Histogram
  - Scatterplot
  - Markov Chain Traceplot
  
:::
::: {.column width="1%" data-latex="{0.04\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::
:::::: {.column width="48%" data-latex="{0.48\textwidth}"}

# Monte Carlos and Simulations

  - [Example 1: Ordinary Least Squares Estimator](https://www.youtube.com/watch?v=JXbB00gUbH8) [8:30]
  - [Using the MonteCarlo Package for Simulations](https://www.youtube.com/watch?v=xxqi6BOo8jo) [6:45]


:::
::::::

