---
title: ''
output:
  pdf_document: default
  html_document:
    css: styles.css
    anchor_sections: no
---

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-165847699-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-165847699-1');
</script>

<link rel="stylesheet" href="styles.css" type="text/css">

# Academic Papers 

## 1. [Estimation of the Number of Components in Nonparametric Multivariate Finite Mixture Models (2021)](https://www.dropbox.com/s/8sp441qoleeijtf/AOS2032.pdf?dl=0) with [Eric Mbakop](https://wpsites.ucalgary.ca/eric-mbakop/).

### **Annals of Statistics** (August, 2021)


---
    
## 2. [Supply Chain Disruptions: Evidence from the Bankruptcy of Hanjin Shipping (2021) ](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3293272)
   
   
### Under revision for re-submission.


---
  
## 3. [Disclosure-Driven Social Engagement in Supply Chains (2021)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3900182) with [Andrew Di Wu](https://sites.google.com/site/diandrewwu/).

### *R&R* at **Manufacturing & Service Operations Management**

### [Winner: POMS College of Sustainable Operations, Best Student Paper Competition](https://poms.org/colleges/csustops/)

---

## 4. [The Effects of Inconsistent Work Schedules on Employe Lateness and Absenteeism]() (2023) with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

### Under Review  at **Manufacturing & Service Operations Management**
<!-- ### [SSRN Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4189723) -->


<!-- ### [Dropbox Link](https://www.dropbox.com/s/hqu3u7kst8qtkc9/Lateness_and_Absenteeism.pdf?raw=1), [SSRN Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4189723) -->


---


## 5. [Human-Computer Interactions in Demand Forecasting and Labor Scheduling Decisions]() (2022) with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534) and [Jorge Tamayo](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1063486)

### *R&R* at **Management Science**
#### First Draft: May 21, 2022. 


---

<!-- ## 6. [The Effects of Fair Workweek Laws on Store Performance: Evidence from Chicago](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4351186) with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534). -->

<!-- ### Submitted -->

<!-- --- -->

## 6. Manager Performance and Labor Scheduling Practices with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

---

## 7. The Effects of the Minimum Wage on Labor Scheduling Practices with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

---

<!-- ## 9. On the Interactions Between the Minimum Wage and Fair Workweek Laws  [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534). -->

<!-- --- -->

## 8. [The Effects of Fair Workweek Laws on Worker Schedules: Evidence from Chicago](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4542956) (2023) with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

### Rejected, with invitation to Resubmit at  **Management Science**
#### Note: New results that include results from Los Angeles' Fair Workweek Law coming soon. 

---

## 9. [The Effects of Fair Workweek Laws on Store Performance: Evidence from Chicago and Los Angeles](https://www.dropbox.com/scl/fi/i1enwo8gpwxbvief4cizz/Chicago_FW.pdf?rlkey=qirv2am8zm7yup75aac4sv4hx&raw=1) with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

#### Note: Original paper included only results from Chicago. New paper that includes results from Los Angeles' Fair Workweek Law coming soon. 
#### First Draft: November 21, 2022. 
#### [SSRN Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4351186)
<!-- #### Note (August 23, 2023). This paper was originally taken down because the corresponding author (Caleb Kwon) wanted to present results that included more data from additional retailers and also include Los Angeles' Fair Workweek law to make the analyses more comprehensive. However, this paper has now been reuploaded due to the existance of articles published after the original upload date of this paper. The unchanged version from November 21, 2022 is presented above.  -->

---


      


# Cases and Teaching Material:

## 1. [Getting Started in R Cloud Studio](https://www.hbs.edu/faculty/Pages/item.aspx?num=59552) with [Chiara Farronato](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=775022).

### **Harvard Business School Tutorial 621-708**, February 2021

## 2. [Innovation at Uber: The Launch of Express POOL Assignment Solutions Video](https://www.hbs.edu/faculty/Pages/item.aspx?num=61245) with [Chiara Farronato](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=775022).

### **Harvard Business School Multimedia/Video Supplement 622-704**, January 2022

## 3. [Innovation at Uber: The Launch of Express POOL Assignment Solutions: Comparing Commuting and Non-Commuting Hours](https://www.hbs.edu/faculty/Pages/item.aspx?num=61244) with [Chiara Farronato](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=775022).

### **Harvard Business School Teaching Note 622-054**, January 2022

## 4. [Innovation at Uber: The Launch of Express POOL Assignment: Comparing Commuting and Non-Commuting Hours](http://hbr.org/product/Innovation-at-Uber--The-L/an/622053-PDF-ENG) with [Chiara Farronato](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=775022).

### **Harvard Business School Supplement 622-053**, January 2022


---


# Resting Papers 

## 1. [The Effect of Employee Lateness and Absenteeism on Store Performance]() with [Ananth Raman](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6534).

### Under Revision


